kyc-messages:
  catalog:
    messages:
      "000":
        code: KYC-CUSTOMER-SERVICE-000
        message: Unexpected Error
        type: ERROR
      "001":
        code: KYC-CUSTOMER-SERVICE-001
        message: The request is invalid
        type: ERROR
      "002":
        code: KYC-CUSTOMER-SERVICE-002
        message: The operation could not be performed
        type: ERROR
      "003":
        code: KYC-CUSTOMER-SERVICE-003
        message: The request is unauthorized
        type: ERROR
      "004":
        code: KYC-CUSTOMER-SERVICE-004
        message: The operation could not be performed
      "005":
        code: KYC-CUSTOMER-SERVICE-005
        message: The customer has already contracted one of the services to acquire