export enum MessageCodes{
    UNEXPECTED_ERROR = '000',
    INVALID_REQUEST = '001',
    UNAVAILABLE_OPERATION = '002',
    UNAUTHORIZED = '003',
    BAD_GATEWAY_SERVICE = '004',
    SERVICE_ALREADY_ACQUIRED = '005',
    SERVICE_NOT_ACQUIRED_OR_INACTIVE = '006'
}