export enum MessageCodes {
  UNEXPECTED_ERROR = '000',
  INVALID_REQUEST = '001',
  UNAVAILABLE_OPERATION = '002',
  UNAUTHORIZED = '003',
  BAD_GATEWAY_SERVICE = '004',
  SERVICE_ALREADY_ACQUIRED = '005',
  SERVICE_NOT_ACQUIRED_OR_INACTIVE = '006',
  FOLIO_NOT_FOUND = '007',
  APPLICATION_FORM_NOT_GENERATED = '008',
  CONTRACT_DOCUMENT_NOT_GENERATED = '009',
}
